export const CONTENTFUL_API_ACCESS_TOKEN =
  process.env.CONTENTFUL_API_ACCESS_TOKEN || "";

export const CONTENTFUL_API_BASE_URL =
  process.env.CONTENTFUL_API_BASE_URL || "";

export const CONTENTFUL_PREVIEW_API_BASE_URL =
  process.env.CONTENTFUL_PREVIEW_API_BASE_URL || "";

export const CONTENTFUL_PREVIEW_API_ACCESS_TOKEN =
  process.env.CONTENTFUL_PREVIEW_API_ACCESS_TOKEN || "";

export const CONTENTFUL_SPACE = process.env.CONTENTFUL_SPACE || "";
